name: Prisma Migrate

# on:
#   schedule:
#     # sets the action to run daily. You can modify this to run the action more or less frequently
#     - cron: "0 0 * * *"
on:
  push:
    branches: [main]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install deps
        run: cd backend && yarn
      - name: Write the .env file
        run: cd backend && touch .env
      - name: Add url to the .env file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > backend/.env
      - run: cd backend && npx prisma migrate dev --name init
      - name: check for file changes
        id: git_status
        run: |
          echo "::set-output name=status::$(git status -s)"
      - name: Commit files
        if: ${{contains(steps.git_status.outputs.status, ' ')}}
        run: |
          git add backend/prisma/
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Update database" -a
      - name: Push changes
        if: ${{contains(steps.git_status.outputs.status, ' ')}}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: Checkout
        uses: actions/checkout@v3
