name: Tests Frontend

on: [push]

jobs:
  vitest-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile
        run: cd frontend && yarn
      - name: Build
        run: cd frontend && yarn build
      - name: Vitest run
        run: cd frontend && yarn test
