name: Tests Backend

on: [push]

jobs:
  tap-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Write the .env file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > backend/.env
      - name: Compile
        run: cd backend && yarn
      - name: Build
        run: cd backend && yarn build
      - name: Prisma Run
        run: cd backend && npx prisma generate
      - name: Tap run
        run: cd backend && yarn test
