name: Tests Backend

on: [push]

jobs:
  vitest-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Compile
        run: cd backend && yarn
      - name: Build
        run: cd backend && yarn build
      - name: Tap run
        run: cd backend && yarn test
